trigger:
  branches:
    include:
      - main  # or your preferred branch

pool:
  name: 'devops-vmss'

# Initial setup (Run once if Apache2 is not installed)
steps:
- script: |


    # Restart Apache 
    sudo systemctl restart apache2
  displayName: 'Deploy to VM'
